FROM debian:bookworm-slim

ARG NATIVE_APP=target/spring-crud
COPY ${NATIVE_APP} /usr/local/bin/java-app/native_app
RUN chmod +x /usr/local/bin/java-app/native_app

EXPOSE 8080

CMD ["/usr/local/bin/java-app/native_app"]